FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /listener


COPY listener.py /listener/

COPY requirements.txt /listener
# Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install "paho-mqtt<2.0.0"
RUN pip install requests

COPY . /listener/

CMD ["python", "listener.py"]