AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GenerateReceiptFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Environment:
        Variables:
          BUCKET_NAME: your-s3-bucket-name
      Policies:
        - S3WritePolicy:
            BucketName: your-s3-bucket-name
      Events:
        Api:
          Type: Api
          Properties:
            Path: /generate-receipt
            Method: post
