name: CI

on:
  push:
    branches:
      - dev  # Adjust according to your project branch
  pull_request:
    branches:
      - dev  # Adjust according to your project branch

jobs:
  build:
    runs-on: ubuntu-latest  # Select appropriate runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install your project dependencies

    - name: Lint backend
      run: |
        pip install pylint
        pip install pylint-fixer
        pylint app/*.py  # Adjust path according to your project structure
        pylint-fixer app/*.py

    - name: Run trivial test for backend
      run: python tests/trivial_test.py  # Create a trivial test that could fail
