name: CI

on:
  push:
    branches:
      - main  # Adjust according to your project branch
      - entrega
      - arreglo_workers
  pull_request:
    branches:
      - main  # Adjust according to your project branch

jobs:
  build:
    runs-on: ubuntu-latest  # Select appropriate runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install your project dependencies

    - name: Lint backend
      run: |
        pip install pylint
        pylint app/*.py  # Adjust path according to your project structure
    - name: Bump version and tag
        run: |
          python bump_version.py
          git push --follow-tags
    
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest app/tests/
