name: CI

on:
  push:
    branches:
      - ci  # Adjust according to your project branch
  pull_request:
    branches:
      - ci  # Adjust according to your project branch

jobs:

  services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
  build:
    runs-on: ubuntu-latest  # Select appropriate runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install your project dependencies

    # - name: Lint backend
    #   run: |
    #     pip install pylint
    #     pip install pylint-fixer
    #     pylint app/*.py  # Adjust path according to your project structure
    #     pylint-fixer app/*.py

    - name: Run trivial test for backend
      run: |
        pip install httpx
        python tests/trivial_test.py  # Create a trivial test that could fail
