name: CI

on:
  push:
    branches:
      - ci  # Adjust according to your project branch
  pull_request:
    branches:
      - ci  # Adjust according to your project branch

jobs:
  build:
    runs-on: ubuntu-latest  # Select appropriate runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install your project dependencies

    - name: Lint backend
      run: |
        pip install pylint
        pip install pylint-fixer
        pylint app/*.py  # Adjust path according to your project structure
        pylint-fixer app/*.py
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest app/tests/
